PracticaCalificada01/Pc01/Pc01/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('eleccionesR/', include ('eleccionesR.urls')),
    path('admin/', admin.site.urls),
]

PracticaCalificada01/Pc01/eleccionesR/urls.py
from django.urls import path

from . import views

app_name = 'eleccionesR'

urlpatterns = [

path('', views.index, name='index'),

path('<int:region_id>/', views.detalle, name='detalle'),

path('<int:region_id>/resultados/', views.resultados, name='resultados'),

path('<int:region_id>/voto/', views.votar, name='votar'),
]

PracticaCalificada01/Pc01/eleccionesR/models.py
from django.db import models

# Create your models here.
class Region(models.Model):
    nombre_region= models.CharField(max_length=200)

class Candidato(models.Model):
    fk_region = models.ForeignKey(Region, on_delete=models.CASCADE)
    nombre_candidato= models.CharField(max_length=200)
    partido_candidato= models.CharField(max_length=200)
    numero_candidato= models.CharField(max_length=200)
    votos = models.IntegerField(default=0)

PracticaCalificada01/Pc01/eleccionesR/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from .models import Candidato, Region

def index(request):
    ultima_region_lista = Region.objects.order_by('-nombre_region')[:5]
    context = {'ultima_region_lista': ultima_region_lista}
    return render(request, 'index.html', context)

def detalle (request, region_id):
    region = get_object_or_404(Region, pk=region_id)
    return render(request, 'detalle.html', {'region': region})

def votar (request, region_id):
    region = get_object_or_404(Region, pk=region_id)
    try:
        selected_candidato = region.candidato_set.get(pk=request.POST['candidato'])
    except (KeyError, Candidato.DoesNotExist):
        return render(request, 'detalle.html', {
            'region' : region,
            'error_message' : "No has seleccionado nada",
        })
    else:
        selected_candidato.votos += 1
        selected_candidato.save()
        return HttpResponseRedirect(reverse('eleccionesR:resultados', args=(region.id,)))


def resultados(request, region_id):
    region = get_object_or_404(Region, pk=region_id)
    return render(request, 'resultados.html', {'region': region})

PracticaCalificada01/Pc01/eleccionesR/templates/detalle.html
<hi>{{ region.nombre_region }}</h1>

    <ul>
        {% for candidato in region.candidato_set.all %}
            <li>{{ candidato.nombre_candidato }} -- {{ candidato.partido_candidato}} -- {{ candidato.numero_candidato}} -- {{ candidato.votos}} -- voto{{ candidato.votos|pluralize }}</li>
        {% endfor %}
    </ul>

    <a href="{% url 'eleccionesR:resultados' region.id %}">Votar de nuevo?</a>
    <a href="{% url 'eleccionesR:index' %}">Ver Regiones</a>

PracticaCalificada01/Pc01/eleccionesR/templates/index.html
<h1>Elecciones Regionales</h1>

{% if ultima_region_lista %}
    <ul>
        {% for region in ultima_region_lista %}
            <li>
                <a href="/eleccionesR/{{ region.id }}/">{{ region.nombre_region }}</a>
            </li>
        {% endfor %}

    </ul>
{% else %}
    <p>No hay registros</p>
{% endif %}

PracticaCalificada01/Pc01/eleccionesR/templates/resultados.html
<h1>{{ region.nombre_region }}</h1>

{% if error_message %} <p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'eleccionesR:votar' region.id %}" method="POST">
    {% csrf_token %}
    {% for candidato in region.candidato_set.all %}
        <input type="radio" name="candidato" id="candidato{{ forloop.counter }}" value="{{candidato.id}}">
        <label for="candidato{{ forloop.counter }}">{{ candidato.nombre_candidato }}</label><br>
    {% endfor %}
    <input type="submit" value="Votar">
</form>
<br/>
<a href="{% url 'eleccionesR:index' %}">Ver Regiones</a>